#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

---
#Service Name, title of your service, used in navigation menus, e.g. Flow Automation.
serviceName: "Flow Automation"
#The current status of your service e.g: beta, stable, deprecated
serviceStatus: "stable"

#Platform service docs is divided into 4 categories. List your pages under the relevant category.
#If a category is not required leave it empty, and it will not be displayed.
category:
  aboutTheService:
    #List the pages in the order you want them to be displayed
    - files:
        #The name of the file for the page
      - fileName: overview.md
        #The name that will be displayed
        displayName: "Overview"
        #Describe the page content, shown when the page link is hovered over
        previewDescription: "Description"

  apiDocumentation:
    #List the pages in the order you want them to be displayed
    - files:
       - fileName: api-guide.md
         displayName: "API Guide"
         previewDescription: "API Guide"