#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "eric-oss-flow-automation-db-pg" "credentials" "kubernetesSecretName" }}
type: Opaque
data:
  # For custom user and password
  custom-user: {{ "faUser" | b64enc | quote }}
  custom-pwd: {{ "password" | b64enc | quote }}

  # For super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  super-pwd: {{ "postgres" | b64enc | quote }}

  # For metrics user and password
  metrics-user: {{ "exporter" | b64enc | quote }}
  metrics-pwd: {{ "exporter" | b64enc | quote }}

  # For replica user and password
  replica-user: {{ "replica" | b64enc | quote }}
  replica-pwd: {{ "replica" | b64enc | quote }}