#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

documents:
  # document name
  - name: eric-oss-flow-automation-sdk-docs
    # file names of files to be packaged in the document
    files:
      - ../sdk-docs/.service_name
      - ../sdk-docs/api-guide.md
      - ../sdk-docs/about-the-service.md
      - ../sdk-docs/overview.md
      - ../sdk-docs/TEMPLATE_VERSION
      - ../sdk-docs/sdk-service-docs-config.yaml