#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.global }}
  {{- if .Values.global.security }}
    {{- if .Values.global.security.tls }}
      {{- if .Values.global.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-oss-flow-automation.name" . }}-internal-cert
  labels:
  {{ include "eric-oss-flow-automation.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-flow-automation.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-oss-flow-automation.name" . }}-secret
    certificateName: clientCert.pem
    privateKeyName: clientPrivateKey.pem
  certificate:
    subject:
      cn: {{ template "eric-oss-flow-automation.name" . }}
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
