#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $serviceMesh := include "eric-oss-flow-automation.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-flow-automation.global-security-tls-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") -}}
  {{- include "eric-oss-flow-automation.db-pg-service-mesh-secret" . }}
---
  {{- include "eric-oss-flow-automation.bragent-service-mesh-secret" . }}
{{- end }}
