#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-oss-flow-automation.name" . }}
  labels:
{{- include "eric-oss-flow-automation.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-flow-automation.annotations" . | nindent 4 }}
spec:
  minAvailable: {{ template "eric-oss-flow-automation.pod-disruption-budget" . }}
  selector:
    matchLabels:
      app: {{ template "eric-oss-flow-automation.name" . }}