#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.global -}}
  {{ if .Values.global.security -}}
    {{ if .Values.global.security.privilegedPolicyClusterRoleName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-oss-flow-automation.name" . }}-psp-binding
  labels:
{{- include "eric-oss-flow-automation.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-flow-automation.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.security.privilegedPolicyClusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-flow-automation.fullname" . }}-sa
    {{- end -}}
  {{- end -}}
{{- end -}}
