#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

eric-oss-flow-automation-db-pg:
  brAgent:
    enabled: false
    backupTypeList:
      - "DEFAULT"
  credentials:
    kubernetesSecretName: eric-oss-flow-automation-secret
    keyForUserId: "custom-user"
    keyForUserPw: "custom-pwd"
    keyForSuperPw: "super-pwd"
    keyForMetricsPw: "metrics-pwd"
    keyForReplicaId: "replica-user"
    keyForReplicaPw: "replica-pwd"
  patroni:
    logLevel: WARNING
  service:
    port: 5432
  highAvailability:
    synchronousModeEnabled: false
    replicaCount: 1
  global:
    security:
      tls:
        enabled: false

probes:
  eric-oss-fa-postgres:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 60
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 60